
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/sigvet_db
        username: sigvet_user
        password: sigvet_pass
    
    jpa:
        hibernate:
            ddl-auto: validate