spring:
    application:
      name: sigvet-api

    datasource:
        url: ${postgres.url}
        username: ${postgres.username}
        password: ${postgres.password}
    jpa:
      hibernate:
          ddl-auto: none
      show-sql: true

    flyway:
      enabled: true

    h2:
        console:
            enabled: false
    servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB
        enabled: true
        

jwt:
  issuer: sigvet-backend-api
  expiresInMinutes: 60