spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/sigvet
        username: sigvet_user
        password: sigvet_pass
    
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
          
    h2:
        console:
            enabled: false
    servlet:
        multipart.max-file-size: 5MB